spring:
  datasource:
    url: jdbc:mysql://aliyun-mysql.dtop.win:3306/discoverydb?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: discovery
    password: discovery2019@pwd
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
